import assert from 'node:assert/strict';
import test from 'node:test';
import {analyzePlayerImport,loadImportStore,readPlayerWorkbook,saveImportVersion} from '../src/import-manager.js';

const current=[{id:'1',roles:'Pc',name:'Rossi',team:'Roma'},{id:'2',roles:'Dc',name:'Bianchi',team:'Milan'}];
const row=(Id,RM,Nome,Squadra,line=3)=>({Id,RM,Nome,Squadra,line});
function zip(files){const encoder=new TextEncoder(),parts=[],central=[];let offset=0;const u16=value=>new Uint8Array([value&255,value>>>8&255]),u32=value=>new Uint8Array([value&255,value>>>8&255,value>>>16&255,value>>>24&255]);for(const [name,contents] of Object.entries(files)){const filename=encoder.encode(name),data=encoder.encode(contents),local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...new Uint8Array(8),...u32(data.length),...u32(data.length),...u16(filename.length),...u16(0),...filename]);parts.push(local,data);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...new Uint8Array(8),...u32(data.length),...u32(data.length),...u16(filename.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...filename]));offset+=local.length+data.length}const centralSize=central.reduce((sum,item)=>sum+item.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(central.length),...u16(central.length),...u32(centralSize),...u32(offset),...u16(0)]);return new Blob([...parts,...central,end]).arrayBuffer()}
const workbook=(sheet='Tutti',headers=['Id','RM','Nome','Squadra'])=>zip({'xl/workbook.xml':`<workbook><sheets><sheet name="${sheet}" r:id="rId1"/></sheets></workbook>`,'xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="rId1" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':`<worksheet><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Titolo</t></is></c></row><row r="2">${headers.map((value,index)=>`<c r="${String.fromCharCode(65+index)}2" t="inlineStr"><is><t>${value}</t></is></c>`).join('')}</row><row r="3"><c r="A3" t="inlineStr"><is><t>1</t></is></c><c r="B3" t="inlineStr"><is><t>Pc</t></is></c><c r="C3" t="inlineStr"><is><t>Rossi</t></is></c><c r="D3" t="inlineStr"><is><t>Roma</t></is></c></row></sheetData></worksheet>`});

test('reads only Tutti with headers on the second row',async()=>assert.deepEqual(await readPlayerWorkbook(await workbook()),[row('1','Pc','Rossi','Roma')]));
test('rejects a workbook without Tutti',async()=>assert.rejects(readPlayerWorkbook(await workbook('Altro')),/Tutti/));
test('rejects wrong headers',async()=>assert.rejects(readPlayerWorkbook(await workbook('Tutti',['Id','Ruolo','Nome','Squadra'])),/RM/));
test('identical import has no delta',()=>{const result=analyzePlayerImport([row('1','Pc','Rossi','Roma'),row('2','Dc','Bianchi','Milan',4)],current);assert.equal(result.delta,0);assert.deepEqual([result.added,result.removed,result.modified],[[],[],[]])});
test('reports an added player',()=>assert.deepEqual(analyzePlayerImport([...current.map((p,i)=>row(p.id,p.roles,p.name,p.team,i+3)),row('3','A','Verdi','Como',5)],current).added.map(p=>p.id),['3']));
test('reports a removed player',()=>assert.deepEqual(analyzePlayerImport([row('1','Pc','Rossi','Roma')],current).removed.map(p=>p.id),['2']));
test('reports duplicate ids and name/team pairs',()=>{const result=analyzePlayerImport([row('1','Pc','Rossi','Roma'),row('1','A','Verdi','Como',4),row('3','A','Rossi','Roma',5)],[]);assert.equal(result.duplicatesId.length,1);assert.equal(result.duplicatesNameTeam.length,1);assert.equal(result.discarded,2)});
test('reports changed ids as matching problems rather than add/remove',()=>{const result=analyzePlayerImport([row('9','Pc','Rossi','Roma')],current.slice(0,1));assert.equal(result.changedIds.length,1);assert.equal(result.added.length,0);assert.equal(result.removed.length,0)});
test('keeps consecutive import metadata and snapshots',()=>{const values=new Map(),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)},analysis=analyzePlayerImport([row('1','Pc','Rossi','Roma')],[]);const first=saveImportVersion({filename:'one.xlsx',analysis,players:analysis.valid,storage,now:new Date('2026-09-04T10:00:00Z')});saveImportVersion({filename:'two.xlsx',analysis,players:analysis.valid,storage,now:new Date('2026-09-05T10:00:00Z')});const history=loadImportStore(storage).history;assert.equal(history.length,2);assert.equal(history[0].previousVersion,first.id);assert.deepEqual(history[1].snapshot,analysis.valid)});
