import {rankPlayers,assignTiers,budgetSummary,tierDepletion} from './domain.js';
import {getFormation,getFormationIds} from './mantraFormations.js';
const raw=await fetch('./data/players.json').then(r=>r.json());
const defaults={budget:1000,rosterSize:34,formation:'3-4-2-1',started:false,slots:[],market:{}};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem('mantra-auction')||'{}'));
const counts={POR:3,DC:8,E:6,C:5,WA:9,PC:3};
if(!state.slots.length) state.slots=Object.entries(counts).flatMap(([c,n])=>Array.from({length:n},(_,i)=>({id:`${c}${i+1}`,category:c,priority:i===0?'Key':i<3?'Starter':'Reserve',originalPlannedBudget:[45,30,20,12,8,5,3,1][i]??1,currentForecastBudget:[45,30,20,12,8,5,3,1][i]??1,playerId:null,actualPurchasePrice:null})));
function players(){return Object.keys(counts).flatMap(cat=>assignTiers(rankPlayers(raw.filter(p=>p.rankingCategory===cat)),state.slots.filter(s=>s.category===cat).length));}
const save=()=>{localStorage.setItem('mantra-auction',JSON.stringify(state));render()};let view='cockpit';
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render()});
function cockpit(){const b=budgetSummary(state.budget,state.slots),ps=players(),dep=tierDepletion(ps,state.market);return `<div class=eyebrow>Live strategy</div><h1>Buonasera, Mister.</h1><div class=grid>${[['Budget iniziale',b.budget],['Speso',b.spent],['Rimanente',b.remaining],['Varianza',b.variance]].map((x,i)=>`<div class="card metric"><label>${x[0]}</label><strong class=${i===2?'lime':''}>${x[1]} <small>cr</small></strong></div>`).join('')}<div class="card wide"><div class=section-head><h2>Rosa</h2><span class=pill>${state.slots.filter(s=>s.playerId).length} / ${state.slots.length}</span></div><p class=muted>${state.slots.filter(s=>!s.playerId).length} slot aperti · ${state.formation}</p></div><div class="card wide"><div class=section-head><h2>Pressione mercato</h2><span class=muted>Disponibili / originali</span></div><div class=pressure>${dep.slice(0,12).map(x=>`<div class=tier><span class=muted>${x.category} · Tier ${x.tier}</span><b>${x.available} / ${x.total}</b><div class=bar><i style="width:${100*x.available/x.total}%"></i></div></div>`).join('')}</div></div></div><div class=section><div class=section-head><h2>Slot prioritari</h2><button class=action onclick="goMarket()">Apri mercato</button></div>${slotTable(state.slots.slice(0,10))}</div>`}
function slotTable(slots){return `<table><thead><tr><th>Slot</th><th>Ruolo</th><th>Priorità</th><th>Baseline</th><th>Forecast</th><th>Acquisto</th></tr></thead><tbody>${slots.map(s=>`<tr><td><b>${s.id}</b></td><td>${s.category}</td><td>${s.priority}</td><td>${s.originalPlannedBudget}</td><td>${s.currentForecastBudget}</td><td>${s.playerId?raw.find(p=>p.id===s.playerId)?.name+' · '+s.actualPurchasePrice:'—'}</td></tr>`).join('')}</tbody></table>`}
function market(){let ps=players();return `<div class=eyebrow>Selezione giocatori</div><h1>Mercato live</h1><div class=filters><input id=q placeholder="Cerca giocatore o squadra…"><select id=cat><option value="">Tutti i ruoli</option>${Object.keys(counts).map(x=>`<option>${x}</option>`)}</select><select id=ms><option value="AVAILABLE">Disponibili</option><option value="">Tutti gli stati</option><option>SOLD</option><option>MY TEAM</option></select></div><div id=marketTable>${playerTable(ps)}</div>`}
function playerTable(ps){return `<table><thead><tr><th>#</th><th>Giocatore</th><th>Ruolo</th><th>Tier</th><th>Asta €</th><th>Quot.</th><th>Hype</th><th>PG / MF</th><th>Status</th><th>Azioni</th></tr></thead><tbody>${ps.slice(0,180).map(p=>{let st=state.market[p.id]?.marketStatus||'AVAILABLE';return `<tr class=${st==='AVAILABLE'?'':'sold'}><td>${p.rankingPosition}</td><td><b>${p.name}</b><br><span class=muted>${p.team} ${p.cups?'· '+p.cups:''}</span></td><td>${p.roles}<br><span class=pill>${p.rankingCategory}</span></td><td>${p.tier}</td><td><b>${p.auctionValue}</b></td><td>${p.quotation}</td><td>${p.hypeFactor??'—'}</td><td>${p.actPg??'—'} / ${p.actMf??'—'}</td><td>${p.status}</td><td>${st==='AVAILABLE'?`<button class="action secondary" onclick="sold('${p.id}')">SOLD</button> <button class=action onclick="buy('${p.id}')">+ MIA</button>`:st}</td></tr>`}).join('')}</tbody></table>`}
function formationSummary(id){const formation=getFormation(id);if(!formation)return `<p class=muted>Modulo non disponibile</p>`;const names={GK:"PORTA",DEF:"DIFESA",MID:"CENTROCAMPO",AM:"TREQUARTI",ATT:"ATTACCO"};return `<div class=formation-summary><b>${formation.label}</b>${formation.lines.map(group=>`<div><span>${names[group.id]}</span><strong>${group.positions.map(position=>position.optionalLabel).join(" · ")}</strong></div>`).join("")}</div>`}
function strategy(){return `<div class=eyebrow>Baseline configurabile</div><h1>Strategia d'asta</h1><div class="card editor"><label>Budget<br><input id=budget type=number value=${state.budget}></label><label>Rosa<br><input id=size type=number min=3 max=34 value=${state.rosterSize}></label><label><br><button class=action onclick=configure()>Salva configurazione</button></label></div><section class="card formation-picker"><div class=section-head><div><h2>Modulo</h2><p class=muted>Scegli uno degli 11 moduli Mantra ufficiali</p></div><span class=pill>11 moduli</span></div><input id=formation type=hidden value="${state.formation}"><div class=formation-options role=radiogroup aria-label="Modulo Mantra">${getFormationIds().map(id=>`<button type=button role=radio aria-checked="${id===state.formation}" class="formation-option${id===state.formation?' selected':''}" data-formation="${id}" onclick="selectFormation('${id}')">${getFormation(id).label}</button>`).join('')}</div></section><div id=formationSummary class="card tactical-card">${formationSummary(state.formation)}</div><div class="card reset-panel section"><div><h2>Ripristina impostazioni</h2><p class=muted>Cancella configurazione, acquisti e stati del mercato, riportando l'app ai valori iniziali.</p></div><button class="action danger-action" onclick=resetAll()>Resetta tutto</button></div><div class=section>${slotTable(state.slots)}</div>`}
function quality(){const missingAge=raw.filter(p=>p.age==null).length,missingPc=raw.filter(p=>!p.pro||!p.contro).length,uncat=raw.filter(p=>!p.rankingCategory).length;return `<div class=eyebrow>Import diagnostics</div><h1>Data quality</h1><div class=grid>${[['Giocatori importati',raw.length],['Età mancanti',missingAge],['Pro / Contro mancanti',missingPc],['Categoria irrisolta',uncat]].map(x=>`<div class="card metric"><label>${x[0]}</label><strong>${x[1]}</strong></div>`).join('')}</div><div class="notice section">Gli arricchimenti storici non sono inventati: i valori non associabili con certezza restano vuoti e richiedono revisione manuale.</div>`}
function render(){document.querySelector('header i').textContent=state.started?'ASTA LIVE':'STRATEGIA';document.querySelector('#app').innerHTML=({cockpit,market,strategy,quality})[view]();if(view==='market'){const filter=()=>{let p=players(),q=document.querySelector('#q').value.toLowerCase(),c=document.querySelector('#cat').value,m=document.querySelector('#ms').value;p=p.filter(x=>(x.name+' '+x.team).toLowerCase().includes(q)&&(!c||x.rankingCategory===c)&&(!m||(state.market[x.id]?.marketStatus||'AVAILABLE')===m));document.querySelector('#marketTable').innerHTML=playerTable(p)};['q','cat','ms'].forEach(id=>document.querySelector('#'+id).oninput=filter)}}
window.goMarket=()=>{view='market';render()};window.selectFormation=id=>{document.querySelector('#formation').value=id;document.querySelectorAll('.formation-option').forEach(button=>{const selected=button.dataset.formation===id;button.classList.toggle('selected',selected);button.setAttribute('aria-checked',selected)});document.querySelector('#formationSummary').innerHTML=formationSummary(id)};window.sold=id=>{state.started=true;state.market[id]={marketStatus:'SOLD'};save()};window.buy=id=>{const p=raw.find(x=>x.id===id),open=state.slots.filter(s=>!s.playerId&&s.category===p.rankingCategory);if(!open.length)return alert('Nessuno slot compatibile aperto');const price=Number(prompt(`Prezzo per ${p.name}?`,p.auctionValue));if(!Number.isFinite(price)||price<1)return;const slot=open[0];slot.playerId=id;slot.actualPurchasePrice=price;state.market[id]={marketStatus:'MY TEAM'};state.started=true;save()};window.configure=()=>{const budget=Number(document.querySelector('#budget').value),size=Number(document.querySelector('#size').value);if(size>34||size<3)return alert('La rosa deve contenere da 3 a 34 giocatori');if(state.slots.filter(s=>s.category==='POR').length!==3)return alert('Sono obbligatori 3 portieri');state.budget=budget;state.rosterSize=size;state.formation=document.querySelector('#formation').value;save()};window.resetAll=()=>{if(!confirm('Vuoi davvero resettare tutte le impostazioni? Configurazione, acquisti e stati del mercato verranno cancellati.'))return;localStorage.removeItem('mantra-auction');location.reload()};render();
