import {CATEGORY_PRIORITY,rankPlayers,assignTiers,budgetSummary,slotPlanSummary,tierDepletion,updateForecasts,updateSlotStrategy} from './domain.js';
import {getFormation,getFormationIds} from './mantraFormations.js';
const cacheKey=Date.now();
const [raw,injuryUpdate]=await Promise.all([
  fetch(`./data/players.json?v=${cacheKey}`,{cache:'no-store'}).then(r=>r.json()),
  Promise.all([fetch(`./data/infortuni.json?v=${cacheKey}`,{cache:'no-store'}),fetch(`./data/infortuni_update.json?v=${cacheKey}`,{cache:'no-store'})]).then(async ([snapshot,update])=>{if(!snapshot.ok||!update.ok)throw new Error('Dataset infortuni non disponibile');await snapshot.json();return update.json()})
]);
const refreshEndpoint=document.querySelector('meta[name="injury-refresh-endpoint"]')?.content?.trim()||'';
const defaults={budget:1000,rosterSize:34,formation:'3-4-2-1',started:false,slots:[],market:{}};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem('mantra-auction')||'{}'));
const counts={POR:3,DC:8,E:6,C:5,WA:9,PC:3};
if(!state.slots.length) state.slots=Object.entries(counts).flatMap(([c,n])=>Array.from({length:n},(_,i)=>({id:`${c}${i+1}`,category:c,priority:i===0?'Key':i<3?'Starter':'Reserve',originalPlannedBudget:[45,30,20,12,8,5,3,1][i]??1,currentForecastBudget:[45,30,20,12,8,5,3,1][i]??1,playerId:null,actualPurchasePrice:null})));
function players(){return Object.keys(counts).flatMap(cat=>assignTiers(rankPlayers(raw.filter(p=>p.rankingCategory===cat)),state.slots.filter(s=>s.category===cat).length));}
const save=()=>{localStorage.setItem('mantra-auction',JSON.stringify(state));render()};let view='cockpit';
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render()});
function cockpit(){const b=budgetSummary(state.budget,state.slots),ps=players(),dep=tierDepletion(ps,state.market);return `<div class=eyebrow>Live strategy</div><h1>Buonasera, Mister.</h1><div class=grid>${[['Budget iniziale',b.budget],['Speso',b.spent],['Rimanente',b.remaining],['Varianza',b.variance]].map((x,i)=>`<div class="card metric"><label>${x[0]}</label><strong class=${i===2?'lime':''}>${x[1]} <small>cr</small></strong></div>`).join('')}<div class="card wide"><div class=section-head><h2>Rosa</h2><span class=pill>${state.slots.filter(s=>s.playerId).length} / ${state.slots.length}</span></div><p class=muted>${state.slots.filter(s=>!s.playerId).length} slot aperti · ${state.formation}</p></div><div class="card wide"><div class=section-head><h2>Pressione mercato</h2><span class=muted>Disponibili / originali</span></div><div class=pressure>${dep.slice(0,12).map(x=>`<div class=tier><span class=muted>${x.category} · Tier ${x.tier}</span><b>${x.available} / ${x.total}</b><div class=bar><i style="width:${100*x.available/x.total}%"></i></div></div>`).join('')}</div></div></div><div class=section><div class=section-head><h2>Slot prioritari</h2><button class=action onclick="goMarket()">Apri mercato</button></div>${slotTable(state.slots.slice(0,10))}</div>`}
function recapValue(value,limit,label){return `<strong class="recap-value ${value<=limit?'recap-ok':'recap-over'}">${value} <small>${label}</small></strong>`}
function slotTable(slots,editable=false){const recap=slotPlanSummary(slots);return `<table class="slot-table"><thead><tr><th>Slot</th><th>Ruolo</th><th>Priorità</th><th>Baseline</th><th>Forecast</th><th>Acquisto</th></tr>${editable?`<tr class="recap-row" aria-label="Riepilogo piano slot"><th>${recapValue(recap.slotCount,34,'slot')}</th><th>${recapValue(recap.roleCount,34,'ruoli')}</th><th><span>Totali</span></th><th data-recap-baseline>${recapValue(recap.planned,1000,'cr')}</th><th></th><th></th></tr>`:''}</thead><tbody>${slots.map(s=>`<tr data-slot-id="${s.id}"><td><b>${s.id}</b></td><td>${editable?(s.category==='POR'?'<span class="fixed-role">POR <small>fisso</small></span>':`<select data-slot-role aria-label="Ruolo ${s.id}">${CATEGORY_PRIORITY.slice(1).map(category=>`<option${category===s.category?' selected':''}>${category}</option>`).join('')}</select>`):s.category}</td><td>${s.priority}</td><td>${editable?`<div class="baseline-cell"><input data-slot-baseline aria-label="Baseline ${s.id}" type="text" inputmode="numeric" value="${s.originalPlannedBudget}"><button class="fill-handle" type="button" aria-label="Trascina per copiare la baseline di ${s.id}" title="Trascina per copiare il valore"></button></div>`:s.originalPlannedBudget}</td><td data-slot-forecast>${s.currentForecastBudget}</td><td>${s.playerId?raw.find(p=>p.id===s.playerId)?.name+' · '+s.actualPurchasePrice:'—'}</td></tr>`).join('')}</tbody></table>`}
function market(){let ps=players();return `<div class=eyebrow>Selezione giocatori</div><h1>Mercato live</h1><div class=filters><input id=q placeholder="Cerca giocatore o squadra…"><select id=cat><option value="">Tutti i ruoli</option>${Object.keys(counts).map(x=>`<option>${x}</option>`)}</select><select id=ms><option value="AVAILABLE">Disponibili</option><option value="">Tutti gli stati</option><option>SOLD</option><option>MY TEAM</option></select></div><div id=marketTable>${playerTable(ps)}</div>`}
function playerTable(ps){return `<table><thead><tr><th>#</th><th>Giocatore</th><th>Ruolo</th><th>Tier</th><th>Asta €</th><th>Quot.</th><th>Hype</th><th>Età</th><th>PG / MF</th><th>Status</th><th>Azioni</th></tr></thead><tbody>${ps.slice(0,180).map(p=>{let st=state.market[p.id]?.marketStatus||'AVAILABLE';return `<tr class=${st==='AVAILABLE'?'':'sold'}><td>${p.rankingPosition}</td><td><b>${p.name}</b><br><span class=muted>${p.team} ${p.cups?'· '+p.cups:''}</span></td><td>${p.roles}<br><span class=pill>${p.rankingCategory}</span></td><td>${p.tier}</td><td><b>${p.auctionValue}</b></td><td>${p.quotation}</td><td>${p.hypeFactor??'—'}</td><td>${p.age??'—'}</td><td>${p.actPg??'—'} / ${p.actMf??'—'}</td><td>${p.status}</td><td>${st==='AVAILABLE'?`<button class="action secondary" onclick="sold('${p.id}')">SOLD</button> <button class=action onclick="buy('${p.id}')">+ MIA</button>`:st}</td></tr>`}).join('')}</tbody></table>`}
function formationSummary(id){const formation=getFormation(id);if(!formation)return `<p class=muted>Modulo non disponibile</p>`;const names={GK:"PORTA",DEF:"DIFESA",MID:"CENTROCAMPO",AM:"TREQUARTI",ATT:"ATTACCO"};return `<div class=formation-summary><b>${formation.label}</b>${formation.lines.map(group=>`<div><span>${names[group.id]}</span><strong>${group.positions.map(position=>position.optionalLabel).join(" · ")}</strong></div>`).join("")}</div>`}
function strategy(){return `<div class=eyebrow>Baseline configurabile</div><h1>Strategia d'asta</h1><div class="card editor"><label>Budget<br><input id=budget type=number value=${state.budget}></label><label>Rosa<br><input id=size type=number min=3 max=34 value=${state.rosterSize}></label><label>Modulo<br><select id=formation>${getFormationIds().map(id=>`<option value="${id}"${id===state.formation?" selected":""}>${getFormation(id).label}</option>`).join("")}</select></label><label><br><button class=action onclick=configure()>Salva configurazione</button></label></div><div id=formationSummary class="card tactical-card">${formationSummary(state.formation)}</div><div class=section><div class=section-head><div><h2>Piano slot</h2><p class=muted>Modifica ruolo e baseline. Trascina il quadratino di una cella per copiarne il valore; i tre ruoli POR sono fissi.</p></div></div>${slotTable(state.slots,true)}</div><div class="card reset-panel section"><div><h2>Ripristina impostazioni</h2><p class=muted>Cancella configurazione, acquisti e stati del mercato, riportando l'app ai valori iniziali.</p></div><button class="action danger-action" onclick=resetAll()>Resetta tutto</button></div>`}
const changeLabel={NEW_INJURY:'NUOVO',RECOVERED:'RIENTRATO',INJURY_UPDATED:'AGGIORNATO',RETURN_UPDATED:'AGGIORNATO',UNCHANGED:'INVARIATO'};
function quality(){const missingAge=raw.filter(p=>p.age==null).length,missingPc=raw.filter(p=>!p.pro||!p.contro).length,uncat=raw.filter(p=>!p.rankingCategory).length,u=injuryUpdate,diagnostics=[...(u.unmatchedRecords||[]).map(x=>`UNMATCHED · ${x.name} · ${x.team||'squadra ignota'}`),...(u.ambiguousRecords||[]).map(x=>`AMBIGUOUS · ${x.name} · ${x.team||'squadra ignota'} · candidati: ${x.candidateIds.join(', ')}`)];return `<div class=eyebrow>Import diagnostics</div><h1>Data quality</h1><div class=grid>${[['Giocatori importati',raw.length],['Età mancanti',missingAge],['Pro / Contro mancanti',missingPc],['Categoria irrisolta',uncat]].map(x=>`<div class="card metric"><label>${x[0]}</label><strong>${x[1]}</strong></div>`).join('')}</div><section class="card section injury-refresh"><div class=section-head><div><h2>Aggiornamento infortuni</h2><p class=muted>Fonte unica: Fantacalcio · ultimo aggiornamento ${u.updatedAt?new Date(u.updatedAt).toLocaleString('it-IT'):'mai'}</p></div><button id=refreshInjuries class=action ${refreshEndpoint?'':'disabled'} ${refreshEndpoint?'':'disabled'}>Aggiorna infortuni</button></div><p id=refreshStatus class=muted>${refreshEndpoint?'Pronto.':'Avvio web non configurato: serve l’endpoint autenticato descritto nella documentazione; nessuna credenziale è esposta nel browser.'}</p><div class=grid>${[['Infortunati attuali',u.currentInjuries],['Matched',u.matched],['Unmatched',u.unmatched],['Ambiguous',u.ambiguous],['Senza rientro',u.missingExpectedReturn],['Nuovi',u.newInjuries],['Rientrati',u.recovered],['Aggiornati',(u.injuryUpdated||0)+(u.returnUpdated||0)]].map(x=>`<div class="metric"><label>${x[0]}</label><strong>${x[1]??0}</strong></div>`).join('')}</div>${(u.errors||[]).map(x=>`<p class=danger>${x}</p>`).join('')}${diagnostics.length?`<h3>Matching da verificare</h3><ul>${diagnostics.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}<h3>Ultime variazioni</h3><div class=changes>${(u.changes||[]).filter(x=>x.type!=='UNCHANGED').map(x=>`<div><span class="change ${x.type}">${changeLabel[x.type]||x.type}</span><b>${x.name}</b><span>${x.team||'—'}</span>${x.type==='RETURN_UPDATED'?`<small>${x.before?.expectedReturn||'—'} → ${x.after?.expectedReturn||'—'}</small>`:''}</div>`).join('')||'<p class=muted>Nessuna variazione disponibile.</p>'}</div></section><div class="notice section">Gli arricchimenti non associabili con certezza restano vuoti e richiedono revisione manuale.</div>`}
async function refreshInjuries(){const button=document.querySelector('#refreshInjuries'),status=document.querySelector('#refreshStatus'),previous=injuryUpdate.updatedAt;button.disabled=true;try{status.textContent='Avvio aggiornamento…';const response=await fetch(refreshEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',credentials:'include'});if(!response.ok)throw new Error(`endpoint HTTP ${response.status}`);status.textContent='Scraping in corso…';for(let attempt=0;attempt<60;attempt++){await new Promise(resolve=>setTimeout(resolve,5000));status.textContent=attempt<5?'Scraping in corso…':'Aggiornamento dati…';const next=await fetch(`./data/infortuni_update.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());if(next.updatedAt&&next.updatedAt!==previous){status.textContent=next.result==='SUCCESS'?'Aggiornamento completato':'Aggiornamento fallito';setTimeout(()=>location.reload(),800);return}}throw new Error('timeout in attesa del workflow')}catch(error){status.textContent=`Aggiornamento fallito: ${error.message}`;button.disabled=false}}

function initBaselineEditor(){
  const inputs=[...document.querySelectorAll('[data-slot-baseline]')];
  const refresh=input=>{
    const row=input.closest('[data-slot-id]'),slot=state.slots.find(item=>item.id===row.dataset.slotId);
    if(!slot.playerId)row.querySelector('[data-slot-forecast]').textContent=input.value;
    const total=inputs.reduce((sum,item)=>sum+Number(item.value||0),0);
    document.querySelector('[data-recap-baseline]').innerHTML=recapValue(total,1000,'cr');
  };
  inputs.forEach(input=>input.oninput=()=>refresh(input));
  let drag=null;
  const fillTo=target=>{
    const end=inputs.indexOf(target);
    if(!drag||end<0)return;
    inputs.forEach((input,index)=>{
      const selected=index>=Math.min(drag.start,end)&&index<=Math.max(drag.start,end);
      input.closest('.baseline-cell').classList.toggle('fill-preview',selected);
      if(selected){input.value=drag.value;refresh(input)}
    });
  };
  document.querySelectorAll('.fill-handle').forEach((handle,index)=>handle.onpointerdown=event=>{
    event.preventDefault();
    drag={start:index,value:inputs[index].value};
    fillTo(inputs[index]);
  });
  document.onpointermove=event=>{
    if(!drag)return;
    const pointed=document.elementFromPoint(event.clientX,event.clientY);
    const target=pointed?.closest('[data-slot-baseline]')??pointed?.closest('[data-slot-id]')?.querySelector('[data-slot-baseline]');
    if(target)fillTo(target);
  };
  document.onpointerup=()=>{
    if(!drag)return;
    drag=null;
    document.querySelectorAll('.fill-preview').forEach(cell=>cell.classList.remove('fill-preview'));
  };
}

function render(){document.querySelector('header i').textContent=state.started?'ASTA LIVE':'STRATEGIA';document.querySelector('#app').innerHTML=({cockpit,market,strategy,quality})[view]();if(view==='quality'&&refreshEndpoint)document.querySelector('#refreshInjuries').onclick=refreshInjuries;if(view==='strategy'){document.querySelector('#formation').onchange=event=>document.querySelector('#formationSummary').innerHTML=formationSummary(event.target.value);initBaselineEditor()}if(view==='market'){const filter=()=>{let p=players(),q=document.querySelector('#q').value.toLowerCase(),c=document.querySelector('#cat').value,m=document.querySelector('#ms').value;p=p.filter(x=>(x.name+' '+x.team).toLowerCase().includes(q)&&(!c||x.rankingCategory===c)&&(!m||(state.market[x.id]?.marketStatus||'AVAILABLE')===m));document.querySelector('#marketTable').innerHTML=playerTable(p)};['q','cat','ms'].forEach(id=>document.querySelector('#'+id).oninput=filter)}}
window.goMarket=()=>{view='market';render()};window.sold=id=>{state.started=true;state.market[id]={marketStatus:'SOLD'};save()};window.buy=id=>{const p=raw.find(x=>x.id===id),open=state.slots.filter(s=>!s.playerId&&s.category===p.rankingCategory);if(!open.length)return alert('Nessuno slot compatibile aperto');const price=Number(prompt(`Prezzo per ${p.name}?`,p.auctionValue));if(!Number.isFinite(price)||price<1)return;const slot=open[0];slot.playerId=id;slot.actualPurchasePrice=price;state.slots=updateForecasts(state.slots);state.market[id]={marketStatus:'MY TEAM'};state.started=true;save()};window.configure=()=>{const budget=Number(document.querySelector('#budget').value),size=Number(document.querySelector('#size').value);if(size>34||size<3)return alert('La rosa deve contenere da 3 a 34 giocatori');const edits=Object.fromEntries([...document.querySelectorAll('[data-slot-id]')].map(row=>[row.dataset.slotId,{category:row.querySelector('[data-slot-role]')?.value??'POR',originalPlannedBudget:row.querySelector('[data-slot-baseline]').value}]));try{state.slots=updateSlotStrategy(state.slots,edits)}catch(error){return alert(error.message)}state.budget=budget;state.rosterSize=size;state.formation=document.querySelector('#formation').value;save()};window.resetAll=()=>{if(!confirm('Vuoi davvero resettare tutte le impostazioni? Configurazione, acquisti e stati del mercato verranno cancellati.'))return;localStorage.removeItem('mantra-auction');location.reload()};render();
